"""
Master list of study sites. Keys are USGS site IDs; values hold metadata.
Add additional sites as needed following the same schema.
"""

MASTER_STUDY_SITES = {
    '01031500': {
        'name': 'Piscataquis River near Dover-Foxcroft, ME',
        'full_name': 'Piscataquis River near Dover-Foxcroft, Maine',
        'state': 'ME',
        'lat': 45.175,
        'lon': -69.315,
        'biome': 'Boreal transition',
        'nwm_comid': 6372479,
        'usgs_id': '01031500',
        'region': 'Northeast',
        'regulation_status': 'Unregulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '01034500': {
        'name': 'Penobscot River, ME',
        'full_name': 'Penobscot River, ME',
        'state': 'ME',
        'lat': 45.236,
        'lon': -68.651,
        'biome': 'Boreal transition',
        'nwm_comid': 6372323,
        'usgs_id': '01034500',
        'region': 'Northeast',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '03479000': {
        'name': 'Watauga River, NC',
        'full_name': 'Watauga River, NC',
        'state': 'NC',
        'lat': 36.215,
        'lon': -81.687,
        'biome': 'Appalachian mixed forest',
        'nwm_comid': 19743430,
        'usgs_id': '03479000',
        'region': 'Southeast',
        'regulation_status': 'Unregulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '04137500': {
        'name': 'Au Sable River, MI',
        'full_name': 'Au Sable River, MI',
        'state': 'MI',
        'lat': 44.436,
        'lon': -83.434,
        'biome': 'Great Lakes mixed forest',
        'nwm_comid': 2184459,
        'usgs_id': '04137500',
        'region': 'Great Lakes',
        'regulation_status': 'Unregulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '05420500': {
        'name': 'Mississippi River at Clinton, IA',
        'full_name': 'Mississippi River at Clinton, IA',
        'state': 'IA',
        'lat': 41.781,
        'lon': -90.252,
        'biome': 'Agricultural intensive',
        'nwm_comid': 4587102,
        'usgs_id': '05420500',
        'region': 'Midwest',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '05464500': {
        'name': 'Cedar River, IA',
        'full_name': 'Cedar River, IA',
        'state': 'IA',
        'lat': 41.972,
        'lon': -91.667,
        'biome': 'Agricultural intensive',
        'nwm_comid': 15565507,
        'usgs_id': '05464500',
        'region': 'Midwest',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '06807000': {
        'name': 'Missouri River at Nebraska City, NE',
        'full_name': 'Missouri River at Nebraska City, NE',
        'state': 'NE',
        'lat': 40.682,
        'lon': -95.847,
        'biome': 'Great Plains',
        'nwm_comid': 16513469,
        'usgs_id': '06807000',
        'region': 'Great Plains',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '08030500': {
        'name': 'Sabine River, TX/LA',
        'full_name': 'Sabine River, TX/LA',
        'state': 'TX/LA',
        'lat': 30.304,
        'lon': -93.744,
        'biome': 'Gulf coastal',
        'nwm_comid': 1776613,
        'usgs_id': '08030500',
        'region': 'Gulf Coast',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '08082500': {
        'name': 'Clear Fork Brazos River, TX',
        'full_name': 'Clear Fork Brazos River, TX',
        'state': 'TX',
        'lat': 32.73,
        'lon': -99.235,
        'biome': 'Semi-arid grassland',
        'nwm_comid': 5489939,
        'usgs_id': '08082500',
        'region': 'South Central',
        'regulation_status': 'Unregulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '08279500': {
        'name': 'Rio Grande at Embudo, NM',
        'full_name': 'Rio Grande at Embudo, NM',
        'state': 'NM',
        'lat': 36.206,
        'lon': -105.964,
        'biome': 'Arid/Semi-arid',
        'nwm_comid': 1752235,
        'usgs_id': '08279500',
        'region': 'Southwest',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '09234500': {
        'name': 'Green River, WY',
        'full_name': 'Green River, WY',
        'state': 'WY',
        'lat': 40.908,
        'lon': -109.423,
        'biome': 'Intermountain',
        'nwm_comid': 17956545,
        'usgs_id': '09234500',
        'region': 'Mountain West',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
    '09504000': {
        'name': 'Oak Creek, AZ',
        'full_name': 'Oak Creek, AZ',
        'state': 'AZ',
        'lat': 34.954,
        'lon': -111.761,
        'biome': 'Desert shrubland/woodland',
        'nwm_comid': 20453378,
        'usgs_id': '09504000',
        'region': 'Southwest',
        'regulation_status': 'Regulated',
        'data_sources': ['ERA5', 'NWM', 'USGS'],
    },
}
